services:

  workbench:
    build:
      context: ./services/api/workbench
      dockerfile: Dockerfile
      target: development
    environment:
      - NEW_RELIC_APP_NAME=WORKBENCH_DEV
      - NEW_RELIC_LICENSE_KEY=test123
      - NEW_RELIC_USER_KEY=test123
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=workbench
      - SCREENER_SHARED_SECRET_TOKEN=foobar
    ports:
      - '3004:3000'
    volumes:
      - ./services/api/workbench:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workbench
    ports:
      - '5432:5432'

